/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DevTeamRouteImport } from './routes/dev-team'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SupervisionRouteImport } from './routes/supervision'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTeamRoute = DevTeamRouteImport.update({
  id: '/dev-team',
  path: '/dev-team',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisionRoute = SupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/dev-team': typeof DevTeamRoute
  '/features': typeof FeaturesRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/store': typeof StoreRoute
  '/supervision': typeof SupervisionRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/dev-team': typeof DevTeamRoute
  '/features': typeof FeaturesRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/store': typeof StoreRoute
  '/supervision': typeof SupervisionRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/dev-team': typeof DevTeamRoute
  '/features': typeof FeaturesRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/store': typeof StoreRoute
  '/supervision': typeof SupervisionRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/departments'
    | '/dev-team'
    | '/features'
    | '/rules'
    | '/staff'
    | '/store'
    | '/supervision'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/departments'
    | '/dev-team'
    | '/features'
    | '/rules'
    | '/staff'
    | '/store'
    | '/supervision'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/departments'
    | '/dev-team'
    | '/features'
    | '/rules'
    | '/staff'
    | '/store'
    | '/supervision'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DevTeamRoute: typeof DevTeamRoute
  FeaturesRoute: typeof FeaturesRoute
  RulesRoute: typeof RulesRoute
  StaffRoute: typeof StaffRoute
  StoreRoute: typeof StoreRoute
  SupervisionRoute: typeof SupervisionRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-team': {
      id: '/dev-team'
      path: '/dev-team'
      fullPath: '/dev-team'
      preLoaderRoute: typeof DevTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervision': {
      id: '/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof SupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DepartmentsRoute: DepartmentsRoute,
  DevTeamRoute: DevTeamRoute,
  FeaturesRoute: FeaturesRoute,
  RulesRoute: RulesRoute,
  StaffRoute: StaffRoute,
  StoreRoute: StoreRoute,
  SupervisionRoute: SupervisionRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
